/**
 * accumulate.js interop shim.
 * The published package resolves as CommonJS. Under both tsx and vite/vitest a
 * namespace import exposes the real members under `.default`; normalize once here.
 */
import * as coreNs from 'accumulate.js/core';
import * as commonNs from 'accumulate.js/common';
import * as encodingNs from 'accumulate.js/encoding';
import * as addressNs from 'accumulate.js/address';

/* eslint-disable @typescript-eslint/no-explicit-any */
export const core: any = (coreNs as any).default ?? coreNs;
export const common: any = (commonNs as any).default ?? commonNs;
export const encoding: any = (encodingNs as any).default ?? encodingNs;
export const address: any = (addressNs as any).default ?? addressNs;

export const ED25519Signature = core.ED25519Signature;
export const EcdsaSha256Signature = core.EcdsaSha256Signature;
export const RsaSha256Signature = core.RsaSha256Signature;
export const DelegatedSignature = core.DelegatedSignature;

/**
 * The signature class per Accumulate signature type.
 *
 * accumulate.js@0.12 encodes all three byte-identically to the Go protocol — verified against vectors
 * generated by the protocol itself (test/fixtures/protocol-signature-vectors.json). Its gap is elsewhere:
 * `Address.keyHash()` throws for the two PKI types. Nothing here calls it — the key page entry is
 * `sha256(publicKey)` for every type, and src/index.ts's SR6 check computes that directly — so the gap
 * costs us nothing and no shim is needed. See docs/DECISIONS.md, "F0: accumulate.js, not a swap".
 */
export const SIGNATURE_CLASS: Record<string, any> = {
  ed25519: ED25519Signature,
  ecdsaSha256: EcdsaSha256Signature,
  rsaSha256: RsaSha256Signature,
};
export const VoteType = core.VoteType; // { Accept:0, Reject:1, Abstain:2, Suggest:3 }
export const sha256: (b: Uint8Array) => Uint8Array = common.sha256;
export const encode: (v: unknown) => Uint8Array = encoding.encode;
export const AccURL = address.URL;
